# Generated by Django 5.2.17 on 2026-09-20 06:35

import django.db.models.deletion
import knowledge.models
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=8)),
                ('file', models.FileField(upload_to=knowledge.models.document_upload_path)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('version', models.CharField(default='v1.0', max_length=16)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='UPLOADING', max_length=16)),
                ('roles_allowed', models.JSONField(default=list, help_text='Role names permitted; empty = inherit KB visibility')),
                ('pages', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('embedding_status', models.CharField(choices=[('QUEUED', 'Queued'), ('INDEXING', 'Indexing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('Organization', 'Organization'), ('Department', 'Department'), ('Restricted', 'Restricted')], default='Organization', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SYNCING', 'Syncing'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bases', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('page', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='organizations.organization')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgebase')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='knowledge.knowledgebase'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_kb_per_org'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['organization', 'knowledge_base'], name='knowledge_d_organiz_d74609_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'knowledge_base'], name='knowledge_d_organiz_6de73b_idx'),
        ),
    ]
